In [1]:
import numpy as np

In [2]:
X = np.array(([0,0,0],[0,0,1],[0,1,0], \
             [0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]), dtype=float)

In [3]:
y = np.array(([1],[0],[0],[0], \
             [0],[0], [0], [1]), dtype=float)

In [4]:
xPredicted = np.array(([0,0,1]), dtype=float)
X = X/np.amax(X,axis= 0)
Xpredicted = xPredicted/np.amax(xPredicted, axis= 0)

In [5]:
lossfile = open("SumSquaredLossList.csv","w")

In [6]:
class Neural_Network(object):
    def __init__(self):
        self.inputLayerSize = 3
        self.outputLayerSIze = 1
        self.hiddenLayerSize = 4
        self.W1 = np.random.randn(self.inputLayerSize, self.hiddenLayerSize)
        self.W2 = np.random.randn(self.hiddenLayerSize, self.outputLayerSIze)
        
    def feedforward(self, X):
        self.z = np.dot(X, self.W1)
        self.z2 = self.activationSigmoid(self.z)
        self.z3 = np.dot(self.z2, self.W2)
        o = self.activationSigmoid(self.z3)
        return o
    
    def backwardPropagate(self, X, y, o):
        self.o_error = y - o
        self.o_delta = self.o_error * self.activationSigmoidPrime(o)
        self.z2_error = self.o_delta.dot(self.W2.T)
        self.z2_delta = self.z2_error * self.activationSigmoidPrime(self.z2)
        self.W1 += X.T.dot(self.z2_delta)
        self.W2 += self.z2.T.dot(self.o_delta)
        
    def trainNetwork(self, X,y):
        o = self.feedforward(X)
        self.backwardPropagate(X,y,o)
    
    def activationSigmoid(self,s):
        return 1/(1+np.exp(-s))
    
    def activationSigmoidPrime(self, s):
        return s*(1-s)
    
    def saveSumSquaredLossList(self,i, error):
        lossfile.write(str(i)+","+str(error.tolist())+ '\n')
        
    def saveweights(self):
        np.savetxt("WeightsLayer1.txt", self.W1, fmt = "%s")
        np.savetxt("WeightsLayer2.txt", self.W2, fmt = "%s")
        
    def predictOutput(self):
        print("Predicted XOR output data based on trained weights: ")
        print("Expected (X1-X3): \n" + str(xPredicted))
        print("Output (Y1): \n" + str(self.feedforward(xPredicted)))
        
myNeuralNetwork = Neural_Network()
trainingEpochs = 1000

In [8]:
for i in range(trainingEpochs):
    print("Epochs #" + str(i)+"\n")
    print("Expected Output of XOR Gate Neural Network: \n" + str(y))
    print("Actual Output from XOR Gate Neural Network: \n" + str(myNeuralNetwork.feedforward(X)))
    Loss = np.mean(np.square(y - myNeuralNetwork.feedforward(X)))
    myNeuralNetwork.saveSumSquaredLossList(i, Loss)
    print("Sum Squared Loss: \n" +str(Loss))
    print("\n")
    myNeuralNetwork.trainNetwork(X,y)
    myNeuralNetwork.saveweights()
    myNeuralNetwork.predictOutput()

Epochs #0

Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.90079009]
 [0.03282866]
 [0.01193269]
 [0.04309639]
 [0.04791085]
 [0.04520762]
 [0.06459271]
 [0.93441758]]
Sum Squared Loss: 
0.003216558259136298


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.0328056]
Epochs #1

Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.90084837]
 [0.0328056 ]
 [0.01192645]
 [0.04306072]
 [0.04788099]
 [0.0451722 ]
 [0.0645462 ]
 [0.93447809]]
Sum Squared Loss: 
0.0032120211191415744


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.03278258]
Epochs #2

Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.90090655]
 [0.03

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.03012765]
Epochs #132

Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.90769616]
 [0.03012765]
 [0.01120521]
 [0.03897697]
 [0.04438331]
 [0.0410953 ]
 [0.05916263]
 [0.9413941 ]]
Sum Squared Loss: 
0.0027082507281443007


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.03010951]
Epochs #133

Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.9077431 ]
 [0.03010951]
 [0.01120034]
 [0.0389497 ]
 [0.0443594 ]
 [0.04106792]
 [0.05912627]
 [0.9414402 ]]
Sum Squared Loss: 
0.002704992738747844


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.03009141]
Epochs #134

Expected Output of XOR Gate Neural Network

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.02778116]
Epochs #277

Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.91383475]
 [0.02778116]
 [0.01057576]
 [0.03549132]
 [0.0412673 ]
 [0.03757927]
 [0.05446917]
 [0.94727322]]
Sum Squared Loss: 
0.0023037399656741214


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.02776673]
Epochs #278

Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.91387291]
 [0.02776673]
 [0.01057189]
 [0.03547014]
 [0.04124799]
 [0.03755781]
 [0.05444037]
 [0.94730884]]
Sum Squared Loss: 
0.002301357541055385


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.02775232]
Epochs #279

Expected Output of XOR Gate Neural Network

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.02587617]
Epochs #423

Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.91892013]
 [0.02587617]
 [0.01006303]
 [0.03272332]
 [0.03870119]
 [0.03476307]
 [0.05067289]
 [0.95191931]]
Sum Squared Loss: 
0.0020001686484806235


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.02586438]
Epochs #424

Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.91895191]
 [0.02586438]
 [0.01005984]
 [0.03270635]
 [0.0386852 ]
 [0.03474575]
 [0.05064943]
 [0.95194771]]
Sum Squared Loss: 
0.001998358001969851


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.0258526]
Epochs #425

Expected Output of XOR Gate Neural Network:

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.02429192]
Epochs #570

Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.92322302]
 [0.02429192]
 [0.00963322]
 [0.03046238]
 [0.03654143]
 [0.03244672]
 [0.04752392]
 [0.95569483]]
Sum Squared Loss: 
0.0017643868668330365


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.02428208]
Epochs #571

Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.92324998]
 [0.02428208]
 [0.00963054]
 [0.03044845]
 [0.03652793]
 [0.0324324 ]
 [0.04750438]
 [0.95571803]]
Sum Squared Loss: 
0.0017629687019766554


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.02427225]
Epochs #572

Expected Output of XOR Gate Neural Networ

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.02294884]
Epochs #718

Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.92692596]
 [0.02294884]
 [0.00926498]
 [0.02857409]
 [0.03469159]
 [0.03050092]
 [0.04485917]
 [0.95883158]]
Sum Squared Loss: 
0.0015762223908054713


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.02294048]
Epochs #719

Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.92694918]
 [0.02294048]
 [0.00926267]
 [0.02856241]
 [0.03468002]
 [0.03048886]
 [0.0448426 ]
 [0.95885092]]
Sum Squared Loss: 
0.001575084494035469


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.02293213]
Epochs #720

Expected Output of XOR Gate Neural Network

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.02181387]
Epochs #864

Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.93009621]
 [0.02181387]
 [0.00895006]
 [0.02699829]
 [0.03311451]
 [0.02886921]
 [0.04261022]
 [0.96143562]]
Sum Squared Loss: 
0.001425529978276165


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.02180665]
Epochs #865

Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.93011652]
 [0.02180665]
 [0.00894805]
 [0.02698832]
 [0.03310443]
 [0.02885886]
 [0.04259591]
 [0.96145206]]
Sum Squared Loss: 
0.0014245951456048679


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.02179943]
Epochs #866

Expected Output of XOR Gate Neural Network

Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.02094191]
Epochs #992

Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.93255824]
 [0.02094191]
 [0.00870527]
 [0.02579983]
 [0.03189407]
 [0.02762335]
 [0.04088393]
 [0.96340666]]
Sum Squared Loss: 
0.0013149021781204962


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.02093549]
Epochs #993

Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.93257645]
 [0.02093549]
 [0.00870345]
 [0.02579104]
 [0.03188506]
 [0.0276142 ]
 [0.04087122]
 [0.96342107]]
Sum Squared Loss: 
0.0013141041755374804


Predicted XOR output data based on trained weights: 
Expected (X1-X3): 
[0. 0. 1.]
Output (Y1): 
[0.02092908]
Epochs #994

Expected Output of XOR Gate Neural Networ